version: '3.8'

services:
  app:
    image: node:16
    container_name: product_assignment_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=post_management
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=secret
    depends_on:
      - database
      - redis
    command: npm run start:dev

  database:
    image: postgres:13
    container_name: product_assignment_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: post_management
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: product_assignment_redis
    ports:
      - '6379:6379'

volumes:
  postgres_data: